// <auto-generated />
using LeThiMaiAnh076.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeThiMaiAnh076.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106071644_Create_table_ltma")]
    partial class Create_table_ltma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LeThiMaiAnh076.LeThiMaiAnh", b =>
                {
                    b.Property<string>("HoTen")
                        .HasColumnType("TEXT");

                    b.Property<float>("Diem")
                        .HasColumnType("REAL");

                    b.Property<int>("MaSV")
                        .HasColumnType("INTEGER");

                    b.HasKey("HoTen");

                    b.ToTable("LeThiMaiAnh");
                });
#pragma warning restore 612, 618
        }
    }
}
